[default]
opaque_types = [
    # rust-bindgen#2240
    "FndrOpaqueInfo", "HFSCatalogFolder", "HFSPlusCatalogFolder", "HFSCatalogFile", "HFSPlusCatalogFile"
]
#impl_debugs = [
#    "IORPCMessage",
#]
replacements = [
    # Foundation name collisions
    "timezone: NSTimeZone, #=># timezone_: NSTimeZone,",
    "componentsInTimeZone : timezone #=># componentsInTimeZone : timezone_",
    "cString: *const ::std::os::raw::c_char, #=># c_string: *const ::std::os::raw::c_char,",
    "stringWithCString : cString #=># stringWithCString : c_string",

    # caregory bug rust-bindgen#2241
    "pub trait NSImage_: Sized + std::ops::Deref {} #=># ",

    # AppKit name collisions
    """invalidRect: NSRect #=># invalidRect_: NSRect,""",
    """setNeedsDisplayInRect: invalidRect #=># setNeedsDisplayInRect: invalidRect_""",
    """shadow: NSShadow #=># shadow_: NSShadow""",
    """setShadow: shadow) #=># setShadow: shadow_)""",
    """fraction: CGFloat #=># fraction_: CGFloat""",
    """fraction : fraction #=># fraction : fraction_""",
    """blendedColorWithFraction : fraction #=># blendedColorWithFraction : fraction_""",
    """extend: BOOL #=># extend_: BOOL""",
    """byExtendingSelection : extend) #=># byExtendingSelection : extend_)""",

    # AppKit - very fragile - rust-bindgen#2241
    """    }
}
impl NSScreen_ for NSScreen {}
pub trait NSScreen_: Sized + std::ops::Deref { #=># }
""",
    """impl NSImage_ for NSImage {}\n\n #=># """,

    # UIKit
    """unsafe fn dividerImageForLeftSegmentState_rightSegmentState_(
        &self,
        state: UIControlState,
        state: UIControlState,
    ) -> UIImage
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send ! (* self , dividerImageForLeftSegmentState : state rightSegmentState : state)
    } #=># unsafe fn dividerImageForLeftSegmentState_rightSegmentState_(
        &self,
        leftState: UIControlState,
        rightState: UIControlState,
    ) -> UIImage
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send ! (* self , dividerImageForLeftSegmentState : leftState rightSegmentState : rightState)
    }"""
]
[SyncServices]
replacements = [
    """formattedRecord: NSDictionary,
        recordId: NSString, #=># formattedRecord: NSDictionary,
        recordId2: NSString,""",
    "newRecordIdentifier : recordId #=># newRecordIdentifier : recordId2",
]
[JavaNativeFoundation]
replacements = [
    "as : javaExceptionType #=># r#as : javaExceptionType",
]
[PDFKit]
replacements = [
    ", PDFView: PDFView #=># , PDFView_: PDFView",
    "setPDFView: PDFView #=># setPDFView: PDFView_",
]
[Quartz]
deps = ["PDFKit"]
[QuickLookUI]
deps = ["PDFKit"]

# iOS
[ARKit]
deps = ["PDFKit"]
[QuickLook]
deps = ["PDFKit"]
